### ISSUE TITLE
can't make in mac 10.11.2

### ISSUE THREAD

**Issue by nonew** [rhcad/x3py#10]
Dear owner
when i make in x3py folder, the following error happen:
kevinMacBook-Pro:x3py Kevin$ make
--Making project x3manager...
../../../source/public/mk/Makefile.pln:29: module.d: No such file or directory
../../../source/public/mk/Makefile.pln:29: plugins.d: No such file or directory
../../../source/public/mk/Makefile.pln:29: workpath.d: No such file or directory
g++ -MM -MF workpath.d -I../../../interface/core -I../../../source/public workpath.cpp
....
make[2]: Nothing to be done for `all'.
--Making project mfcapp1...
make[3]: Nothing to be done for`all'.
--Making project mfcwnd...
make[3]: Nothing to be done for `all'.

Thank you!

**Comment by rhcad** [comment]
VC++ MFC projects are used only on Windows.

Thanks
Zhang

**Comment by rhcad** [comment]
Please try again for the commit 0c88b64916b54c49af2f0430fac1f785ced79861.
