### ISSUE TITLE
how to build your project with codeblocks

### ISSUE THREAD

**Issue by nonew** [rhcad/x3py#12]
Dear owner,
Can you guide me to config codeblocks so that I can compile and debug your project x3pyu with it, which is convenient to have IDE debug tool.
Thanks!

**Comment by rhcad** [comment]
Please see the [wiki page](https://github.com/rhcad/x3py/wiki/CreateProject#create-a-plugin-project-with-codeblocks).

**Comment by rhcad** [comment]
## Create a plugin project with CodeBlocks

1. Create a new project using the wizard such as 'Shared library'.

   - Language: C++.
   - Let's assume the position of new project is `x3py/projects/codeblocks`.

2. Set the project build options (Search directories | Compiler).

   `../../../interface/core` and your customized paths such as `../../../interface/example`.

3. Add *.h and *.cpp files of your plugin, such as `x3py/source/example/plsimple`.
