### ISSUE TITLE
关于设置__iidmap缓存的作用

### ISSUE THREAD

**Issue by higithubhi** [rhcad/x3py#17]
设置iidmap缓存的作用如下：
当clsid不为空的时候，没有副作用，
在clsid为空的情况下，可以通过iid来创建一个之前创建的插件对象，例如我的程序中如下使用场景：
主程序创建了一个log插件对象并配置好了，其他插件系统里面不需要知道log插件的clsid，只需要知道log插件的iid，即这样就可以支持创建：
x3::Object\<ILog\> log;
log.create();
log->setModuleName(_getClassName());
综合考虑，建议加入iidmap缓存，可以支持更多场景，也并不影响原本通过clsid来创建插件对象的问题

**Comment by rhcad** [comment]
我觉得这种用法不标准--只指定IID就创建对象。同时需要使用log插件也不差知道clsid这点。

**Comment by higithubhi** [comment]
创建对象必须通过指定接口和clsid是没有疑问的
但是加入缓存，这个缓存唯一生效方式就是这个接口曾经创建过，才能支持后续重复创建这种方式，这种方式就相当于一种语法糖。
而且还有一个重要因素：
如果其他插件必须要知道clsid，那么例如log这种每个模块都使用的接口，要么硬编码在代码里，要么通过配置文件，为什么不能通过主程序来控制选择了某个log实现，其他插件其实不关心具体是谁（clsid）实现log功能，只需要有log接口输出的能力，来完成整个程序系统的log输出。从这个角度来看，这也更符合插件的思想，插件基于接口协作，除非必要，插件不需要指定另外一个接口的具体实现，必须clsid就意味这绑定了相关插件的实现

**Comment by rhcad** [comment]
如果不需要其他插件知道clsid，可以做成由主模块将相关接口对象广播给其他插件，或者其他插件向管理器对象请求委托创建。

**Comment by higithubhi** [comment]
是有很多机制可以实现这个方式，不过我觉得这样实现比较自然而已，这个_iidmap正是缓存在插件管理器里面，就是插件管理器委托创建的一种方式。
感谢你贡献出这么优秀的项目。
