### ISSUE TITLE
有部分函数实现写在头文件里面；文件结构不好，引用到项目中会有各种包含路径问题

### ISSUE THREAD

**Issue by lostcoder0812** [rhcad/x3py#7]
感觉此库代码质量很一般，开发者想引用到实际项目中的话要慎重。

**Comment by rhcad** [comment]
请具体指出有哪些问题，欢迎客观评论。

**Comment by zapline** [comment]
写在头文件里的函数用了inline 
我也没使用，但文件结构看起来是作者精心整理过的，有哪里不好说说嘛

**Comment by lostcoder0812** [comment]
@rhcad 额 想不到还在关注的啊。我语气有点问题，先道个歉。
有几个地方我认为写得不好:
x3py\interface\core\module\pluginimpl.h 186行:
```
#ifndef CREATEOBJECTIMPL
#define CREATEOBJECTIMPL
LOCALAPI bool createObject(const char* clsid, long iid, IObject** p)
{
    if (!x3InternalCreate(clsid, iid, p) && *clsid && s_manager)
    {
        typedef bool (*F)(const char*, long, IObject**);
        F f = (F)GetProcAddress(s_manager, "x3CreateObject");
        return f && f(clsid, iid, p);
    }
    return *p != NULL;
}
#endif
```

这里个头文件里面的全局函数包含了实现，在包含到工程里面会出现符号重定义的问题;

x3py\portability\uniximpl.h, 184行:

```
long InterlockedIncrement(long* p)
{
    return ++(*p);
}

long InterlockedDecrement(long* p)
{
    return --(*p);
}
```

这里不想吐槽了

interface\core\utilfunc\lockrw.h，54行；

```
    bool canRead() const
    {
        return _type > 0;
    }

    bool canWrite() const
    {
        return 2 == _type;
    }
```
不太明白这个锁的实现，如果不能获取锁的话，不应该是一直阻塞在调用的地方么？库里面很多地方都用到了这个锁，canRead如果返回false就直接跳过了，感觉没起到读写锁的作用

**Comment by rhcad** [comment]
pluginimpl.h 在每个工程中只会有一个cpp文件去包含它，不存在重定义问题，在文件头中也有说明。

uniximpl.h 的InterlockedIncrement没有使用复杂的锁定机制，因为我很少使用Linux，感兴趣的可去实现它。

lockrw.h 是读写锁，使用者可以选择不永久等待阻塞，使用 canRead 检测锁定成功否。不能避免应用程序因使用顺序造成的死锁，所以提供了有限时间等待。
