### ISSUE TITLE
有没有函数可以列举出满足某个接口的所有插件

### ISSUE THREAD

**Issue by www2sssyyy** [rhcad/x3py#8]
有没有函数可以列举出满足某个接口的所有插件，比如我做了5个绘图的插件，他们都有Draw方法，然后x3py能不能在不知道clsid的情况下，调用函数列举出所有满足条件的插件？

**Comment by rhcad** [comment]
没有这样的函数。在插件管理器缓存了类ID串和类的工厂函数，并没有缓存接口列表。如果要遍历指定接口的类，则需要对每个类ID依次创建一个指定IID的临时对象，显然这太耗资源。

解决方法：你可在这5个绘图的插件中向某个单实例接口对象注册绘图者信息，这样就可以通过这个单实例接口对象查询到相关信息。

**Comment by www2sssyyy** [comment]
了解了，谢谢
