### ISSUE TITLE
Can`t make on mac os x 10.10

### ISSUE THREAD

**Issue by taotaowong** [rhcad/x3py#9]
问题描述：
平台： osx 10.10,   QT5.5.0 
编译 x3py-master 下的Makefile时出现以下错误：
文件：  /x3py-master/source/uidemo/qtapp1/main.cpp
下的头文件 <QApplication>无法找到。

求助：解决方案。

**Comment by rhcad** [comment]
需要设置环境变量，见config.mk和Makefile.qt4
- `QT4_INCLUDE`: QT头文件路径
- `QT4_LIB`: QT库文件路径

```
ifndef QT4_INCLUDE
ifdef QTDIR
QT4_INCLUDE =$(QTDIR)/include
QT4_LIB     =$(QTDIR)/lib
QT4_BIN     =$(QTDIR)/bin/
endif
endif

ifdef QT4_INCLUDE

INCLUDES += -I"$(QT4_INCLUDE)" \
            -I"$(QT4_INCLUDE)/QtCore" \
            -I"$(QT4_INCLUDE)/QtGui" \
            -I"$(QT4_INCLUDE)/qtmain" \
            -I"$(OBJDIR)" \
            -DQT_CORE_LIB -DQT_GUI_LIB
```

**Comment by taotaowong** [comment]
新编译问题：
--Making project qtapp1...
../../../source/public/mk/Makefile.qt4:85: main.d: No such file or directory
g++ -MM -MF main.d -I../../../interface/core -I../../../source/public -I../../../interface/example -I"/Applications/Qt5.5.0/5.5/clang_64/include" -I"/Applications/Qt5.5.0/5.5/clang_64/include/QtCore" -I"/Applications/Qt5.5.0/5.5/clang_64/include/QtGui" -I"/Applications/Qt5.5.0/5.5/clang_64/include/qtmain" -I"._qt" -DQT_CORE_LIB -DQT_GUI_LIB main.cpp
main.cpp:1:10: fatal error: 'QApplication' file not found
#include <QApplication>
         ^
1 error generated.
make[3]: *** [main.d] Error 1
make[2]: *** [qtapp1] Error 2
make[1]: *** [uidemo] Error 2
make: *** [source] Error 2
 
求助： 谢谢

**Comment by rhcad** [comment]
1. 在 `.bash_profile` 中添加 `export QTDIR=~/Qt/5.5/clang_64`
2. 在QT安装目录 `~/Qt/5.5/clang_64/include` 下创建 QtCore、QtGui、QtWidgets 文件夹
3. 复制 QtCore、QtGui、QtWidgets 的头文件：
    - `clang_64/lib/QtCore.framework/Headers/*.h` 到 `clang_64/include/QtCore`
    - `clang_64/lib/QtGui.framework/Headers/*.h` 到 `clang_64/include/QtGui`
    - `clang_64/lib/QtWidgets.framework/Headers/*.h` 到 `clang_64/include/QtWidgets`
